CREATE DATABASE saas DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE saas;

CREATE TABLE IF NOT EXISTS users (
	user_id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,	
	website VARCHAR(30) NOT NULL UNIQUE KEY,
    email VARCHAR(100) NOT NULL UNIQUE KEY,
	password VARCHAR(50) NOT NULL,
	active TINYINT(1) UNSIGNED NOT NULL DEFAULT '1'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;

CREATE TABLE IF NOT EXISTS about_page (
	about_page_id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
	user_id INT UNSIGNED NOT NULL,
	FOREIGN KEY (user_id) REFERENCES users(user_id),
	theme VARCHAR(50) NOT NULL,
	title VARCHAR(50) NOT NULL,
	sub_title VARCHAR(50) NOT NULL,
	skill_one VARCHAR(50) NOT NULL,
	skill_two VARCHAR(50) NOT NULL,
	skill_three VARCHAR(50) NOT NULL,
	job_title VARCHAR(50) NOT NULL,
	job_start_date VARCHAR(20) NOT NULL,
	job_end_date VARCHAR(20) NOT NULL,
	job_responsibilities TEXT NOT NULL,
	school_name VARCHAR(50) NOT NULL,
	degree_program VARCHAR(50) NOT NULL,
	degree_type VARCHAR(50) NOT NULL,
	degree_status VARCHAR(50) NOT NULL,
	school_comments TEXT,
	summary TEXT NOT NULL,
	objective TEXT NOT NULL,
	git_url VARCHAR(50),
	fb_url VARCHAR(50),
	linked_url VARCHAR(50),
	phone VARCHAR(10) NOT NULL,
	contact_email VARCHAR(50) NOT NULL,
	city VARCHAR(50) NOT NULL,
	states VARCHAR(50) NOT NULL,
	active TINYINT(1) UNSIGNED NOT NULL DEFAULT '1'
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1;
